apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      containers:
        - name: property
          image: lnguyendev/m_property
          env:
            - name: MONGO_URI
              value: 'mongodb://property-mongo-srv:27017/property'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: property-srv
spec:
  selector:
    app: property
  ports:
    - name: property
      protocol: TCP
      port: 3000
      targetPort: 3000
